### ISSUE TITLE
SSL Certificate is down :(

### ISSUE THREAD

**Issue by Aevyz** [mammuth/TUM.sexy#164]
Certificate seems to have expired at 6:11 PM today.

**Comment by kordianbruck** [comment]
Working on it.

**Comment by kordianbruck** [comment]
Finished. Lord this was a bunch of problems. I've simplified the setup a bit using docker & traefik on a single node, instead of a kubernetes cluster, so things should be easier to debug for the next time. 

Still, acme.sh is not the best piece of software. I'm checking out, if I can add a dns challenge solver somehow to traefik directly.
