### ISSUE TITLE
add a OpenSearch Description Document

### ISSUE THREAD

**Issue by zepatrik** [mammuth/TUM.sexy#46]
The website isn't really a search engine, but I configured my browser to offer it as one. With a [OpenSearch Description Document](http://www.opensearch.org/Home) browsers would get a working link (e.g. [search term].tum.sexy) and offer it in the search engine settings.

**Comment by kordianbruck** [comment]
Why is this useful? Or maybe I just don't get the point?

So you want to search on google by going to a subdomain on tum.sexy, right?

**Comment by zepatrik** [comment]
In [this video](https://youtu.be/pVvWiAtkz64) you can see the search feature of chrome in action, in the picture below the needed config for this. The correct configuration can be added by the OpenSearch Description Document to the Settings page shown below so the user can use it instantly.

![bildschirmfoto vom 2017-01-13 19-41-41](https://cloud.githubusercontent.com/assets/5354445/21941524/6518ddf0-d9c9-11e6-8610-d259a4368732.png)

**Comment by mammuth** [comment]
Ah, got it! 
Interesting, I didn't know OpenSearch Description until now, although I'm using it in chrome pretty intensive ☺️ 

However, in my opinion, it doesn't make that much sense for our site at the current state. First of all the number of "search terms" is pretty limited. Second, they're actually no search terms, since you need to know the exact phrasing. Furthermore, I feel like it's faster to type "hunger" into the omnibox and select the suggested "hunger.tum.sexy" from the history (I see, that this point may be invalid for people who delete their history regularly or even when the browser closes).

But since it's nothing negative to users who are not interested in it, but might provide value for users that are interested in it, I'd be fine with adding it - feel free to do so in a PR! 

Thank you for sharing your thoughts.

**Comment by zepatrik** [comment]
Am I right that you are using the header(...) function to redirect?
Then I think the only possibility is to add it to the index because you need to add the document in the head of the html.

**Comment by zepatrik** [comment]
#47 so I did a pull request, hope the changes are fine with you

**Comment by mammuth** [comment]
Closed by #47
