### ISSUE TITLE
DNS settings

### ISSUE THREAD

**Issue by kordianbruck** [mammuth/TUM.sexy#58]
```
$ dig hunger.tum.sexy
...
;; ANSWER SECTION:
hunger.tum.sexy.	839	IN	A	162.255.119.250
```

**Comment by mammuth** [comment]
Same for me. But I have no idea what's going on here:
<img width="1118" alt="screen shot 2017-04-05 at 15 07 52" src="https://cloud.githubusercontent.com/assets/3121306/24706868/a9be64ce-1a11-11e7-8bbc-79ae116efb63.png">

**Comment by jpbernius** [comment]
There are more records hidden behind the `SHOW MORE` Button!

**Comment by krenzland** [comment]
Alright. The reason for the strange DNS record was the URL Redirect Record for hunger.
Both @mammuth and I tried to remove it, but failed due to Namecheap's buggy website.

After contacting their support team, this was fixed. They also notified me that the "\*.tum.sexy" record is incorrect, because it apparently creates a record for "\*.tum.sexy.tum.sexy". 

The new DNS settings look like this:
![new DNS settings](https://cloud.githubusercontent.com/assets/1886744/24807487/a57998ae-1bb8-11e7-816c-e65221891da2.png)

A quick check confirms that the DNS records are now working as intended:
```
$ dig tum.sexy | grep "ANSWER SECTION" -C +1

;; ANSWER SECTION:
tum.sexy.		1788	IN	A	37.120.188.245

$ dig hunger.tum.sexy | grep "ANSWER SECTION" -C +1 

;; ANSWER SECTION:
hunger.tum.sexy.	1794	IN	A	37.120.188.245
```

**Comment by kordianbruck** [comment]
#profis

**Comment by kordianbruck** [comment]
Thanks for fixing this @krenzland

**Comment by lukf** [comment]
You might want to consider switching to iwantmyname.com when the tum.sexy domain is set to renew. More reliable and friendly than Namecheap in my experience. Generally, I’d also recommend managing DNS with Cloudflare. You can disable their reverse-proxy if you have objections to the MITM-style handling of TLS they do by default.

**Comment by kordianbruck** [comment]
This happen just as they launched their new interface. Now it works quite well. Thanks for the suggestion.

I'm no friend of cloudflare - rather working on setting up my own DNS system.
