### ISSUE TITLE
Add search/filter for redirects

### ISSUE THREAD

**Issue by mammuth** [mammuth/TUM.sexy#81]
As discussed in #78 a search/filter box might be cool to filter the list of available links.

The filtering should be implemented in-place on the client side without the need of a page refresh.

**Comment by hbirler** [comment]
I got a working test/demo at https://hbirler.github.io/StaticSearchJs/index.html
Is this what you had in mind?

**Comment by mammuth** [comment]
Nice approach!

Hm, maybe it would be useful for your library to make it more explicit/configurable which DOM elements should be filtered and which not? Otherwise such searches are possible but not really useful:

![image](https://user-images.githubusercontent.com/3121306/31963254-5729e4fc-b900-11e7-8945-af8adb2d95bb.png)

**Comment by hbirler** [comment]
Would using HTML5 Custom Data Attributes make sense?
Example:
`<h2 data-no-filter> </h2>`

**Comment by hbirler** [comment]
It may also make sense to allow some elements to force display its siblings. If someone searches for "3. s" this might mean that he/she is looking for all the 3rd semester lectures.
This might complicate the tree traversal somewhat, so just adding "3. Semester" as a hidden value to the siblings may be easier to do.

```
<h4 data-filter-forcesiblings>3. Semester</h4>
<li>Analysis für Informatiker — <a href="http://anal.tum.sexy/">anal.tum.sexy</a></li>
```

vs

```
<h4>3. Semester</h4>
<li data-filter-additional="3. Semester">Analysis für Informatiker — <a href="http://anal.tum.sexy/">anal.tum.sexy</a></li>
```

**Comment by hbirler** [comment]
"forcesiblings" turned out to be somewhat difficult. But I added "nofilter", "additional", "forceadditional" as supported data attributes.

nofilter: node isn't filtered
additional: if pattern is contained in additional, the node is displayed
forceadditional: if pattern is contained in additional, the node and all its children are displayed

Nodes that are formatting tags (such as <b>, <em>, <h*>) push their additional and forceadditional attributes up to their first ancestor that isn't a formatting tag (such as <div>). A custom list of such tags can be sent to the library as a parameter.

**Comment by kordianbruck** [comment]
Wouldn't it be way easier to add a `data-search-value` to anything that we want to be searched? I mean theres a lot of markup in the website and it really is kinda inefficient to mark everything we *don't* want to be searched.

**Comment by hbirler** [comment]
If we only search the data-search-value, we can't do highlighting.

**Comment by kordianbruck** [comment]
@hbirler not sure that highlighting is that needed. Mostly you will type 2-3 letters and that will be fine.
